### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by githubteacher** [githubschool/github-games-sbodepu#1]
When attempting to access this at https://githubschool.github.io/github-games-sbodepu, I am getting a 404. This could be caused by a couple things:

 - GitHub pages needs to be enabled on master. You can fix this in the repository settings.
- the index.html file is incorrectly named inde.html. We will fix this together in class.

 Can you please fix the first bullet @sbodepu?

**Comment by sbodepu** [comment]
Fixed file name - 4b9cd2106a404b8365a4ae0a4e6250246f3c8afd
